# Generated by Django 4.1.7 on 2023-02-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.IntegerField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('costo', models.IntegerField()),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.IntegerField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('idobrasocial', models.IntegerField(db_column='idobraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'obrasocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(max_length=45)),
                ('userinstagram', models.CharField(blank=True, db_column='userInstagram', max_length=60, null=True)),
                ('userfacebook', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idturno', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoHasEspecialidad',
            fields=[
                ('medico_dni', models.OneToOneField(db_column='Medico_dni', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Crud.medico')),
            ],
            options={
                'db_table': 'medico_has_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObrasocialHasMedico',
            fields=[
                ('obrasocial_idobrasocial', models.OneToOneField(db_column='obraSocial_idobraSocial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Crud.obrasocial')),
            ],
            options={
                'db_table': 'obrasocial_has_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObrasocialHasPaciente',
            fields=[
                ('obrasocial_idobrasocial', models.OneToOneField(db_column='obraSocial_idobraSocial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Crud.obrasocial')),
            ],
            options={
                'db_table': 'obrasocial_has_paciente',
                'managed': False,
            },
        ),
    ]
