# Generated by Django 4.1.7 on 2023-02-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicohasespecialidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='obrasocialhasmedico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='obrasocialhaspaciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
    ]
