# Generated by Django 4.1.7 on 2023-02-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_alter_consulta_options_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicohasespecialidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obrasocialhasmedico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obrasocialhaspaciente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'managed': False},
        ),
    ]
