# Generated by Django 4.1.7 on 2023-02-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0003_alter_consulta_options_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.RemoveField(
            model_name='medicohasespecialidad',
            name='medico_dni',
        ),
        migrations.RemoveField(
            model_name='obrasocialhasmedico',
            name='obrasocial_idobrasocial',
        ),
        migrations.RemoveField(
            model_name='obrasocialhaspaciente',
            name='obrasocial_idobrasocial',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='MedicoHasEspecialidad',
        ),
        migrations.DeleteModel(
            name='Obrasocial',
        ),
        migrations.DeleteModel(
            name='ObrasocialHasMedico',
        ),
        migrations.DeleteModel(
            name='ObrasocialHasPaciente',
        ),
    ]
