# Generated by Django 4.1.7 on 2023-02-18 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Crud', '0004_delete_consulta_delete_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.IntegerField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('idobrasocial', models.IntegerField(db_column='idobraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contrasena', models.CharField(max_length=45)),
                ('userinstagram', models.CharField(blank=True, db_column='userInstagram', max_length=60, null=True)),
                ('userfacebook', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idturno', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('paciente_dni', models.ForeignKey(db_column='Paciente_dni', on_delete=django.db.models.deletion.DO_NOTHING, to='Crud.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.IntegerField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('costo', models.IntegerField()),
                ('medico_dni', models.ForeignKey(db_column='Medico_dni', on_delete=django.db.models.deletion.DO_NOTHING, to='Crud.medico')),
                ('turno_idturno', models.ForeignKey(db_column='turno_idturno', on_delete=django.db.models.deletion.DO_NOTHING, to='Crud.turno')),
            ],
        ),
        migrations.CreateModel(
            name='ObrasocialHasPaciente',
            fields=[
                ('obrasocial_idobrasocial', models.OneToOneField(db_column='obraSocial_idobraSocial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Crud.obrasocial')),
                ('paciente_dni', models.ForeignKey(db_column='Paciente_dni', on_delete=django.db.models.deletion.DO_NOTHING, to='Crud.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ObrasocialHasMedico',
            fields=[
                ('obrasocial_idobrasocial', models.OneToOneField(db_column='obraSocial_idobraSocial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Crud.obrasocial')),
                ('medico_dni', models.ForeignKey(db_column='Medico_dni', on_delete=django.db.models.deletion.DO_NOTHING, to='Crud.medico')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoHasEspecialidad',
            fields=[
                ('medico_dni', models.OneToOneField(db_column='Medico_dni', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Crud.medico')),
                ('especialidad_idespecialidad', models.ForeignKey(db_column='Especialidad_idEspecialidad', on_delete=django.db.models.deletion.DO_NOTHING, to='Crud.especialidad')),
            ],
        ),
    ]
